# Generated by Django 2.2.1 on 2019-05-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shhost',
            name='ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
