# Generated by Django 2.2.1 on 2019-05-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LA', '0003_auto_20190528_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shhost',
            name='compliant',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='shhost',
            name='lastscantime',
            field=models.DateTimeField(null=True),
        ),
    ]
