# Generated by Django 2.2.1 on 2019-06-06 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LA', '0004_auto_20190528_0316'),
    ]

    operations = [
        migrations.CreateModel(
            name='REDHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=200)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('owner', models.CharField(max_length=200)),
                ('os', models.CharField(max_length=200, null=True)),
                ('lastcu', models.CharField(max_length=200, null=True)),
                ('compliant', models.BooleanField(default=False, null=True)),
                ('lastscantime', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='REDVirtualMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_name', models.CharField(max_length=200)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('owner', models.CharField(max_length=200)),
                ('os', models.CharField(max_length=200, null=True)),
                ('lastcu', models.CharField(max_length=200, null=True)),
                ('compliant', models.BooleanField(default=True)),
                ('lastscantime', models.DateTimeField(null=True)),
                ('loc_host', models.ForeignKey(db_column='host_name', on_delete=django.db.models.deletion.CASCADE, to='LA.REDHost')),
            ],
        ),
        migrations.CreateModel(
            name='SHVirtualMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_name', models.CharField(max_length=200)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('owner', models.CharField(max_length=200)),
                ('os', models.CharField(max_length=200, null=True)),
                ('lastcu', models.CharField(max_length=200, null=True)),
                ('compliant', models.BooleanField(default=True)),
                ('lastscantime', models.DateTimeField(null=True)),
                ('loc_host', models.ForeignKey(db_column='host_name', on_delete=django.db.models.deletion.CASCADE, to='LA.SHHost')),
            ],
        ),
        migrations.DeleteModel(
            name='VirtualMachine',
        ),
    ]
