# Generated by Django 2.2.2 on 2019-06-13 04:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('LA', '0005_auto_20190606_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='redhost',
            name='installedupdate',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='redhost',
            name='rebootrequired',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='redhost',
            name='vms',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='redvirtualmachine',
            name='installedupdate',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='redvirtualmachine',
            name='rebootrequired',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='redvirtualmachine',
            name='vmid',
            field=models.UUIDField(default=uuid.UUID('3c79e866-3cae-42e7-9791-aba8648d8c31')),
        ),
        migrations.AddField(
            model_name='shhost',
            name='installedupdate',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='shhost',
            name='rebootrequired',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shhost',
            name='vms',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='shvirtualmachine',
            name='installedupdate',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='shvirtualmachine',
            name='rebootrequired',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shvirtualmachine',
            name='vmid',
            field=models.UUIDField(default=uuid.UUID('4568bb88-a3b2-4c81-9d2c-263eebe6b997')),
        ),
    ]
