# Generated by Django 2.2.2 on 2019-06-13 10:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('LA', '0006_auto_20190612_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='redhost',
            name='obsolete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shhost',
            name='obsolete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='redvirtualmachine',
            name='vmid',
            field=models.UUIDField(default=uuid.UUID('04f97b39-aaa8-465d-ade9-2b98c7828a3e')),
        ),
        migrations.AlterField(
            model_name='shvirtualmachine',
            name='vmid',
            field=models.UUIDField(default=uuid.UUID('5d8cf33e-db7a-4b6c-b091-0c51177237bc')),
        ),
    ]
