# Generated by Django 2.2.2 on 2019-06-13 10:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('LA', '0007_auto_20190613_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redvirtualmachine',
            name='vmid',
            field=models.UUIDField(default=uuid.UUID('ac37e530-4e3d-4f97-bc57-644e91c02662')),
        ),
        migrations.AlterField(
            model_name='shhost',
            name='compliant',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='shhost',
            name='installedupdate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shhost',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shhost',
            name='lastcu',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shhost',
            name='lastscantime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shhost',
            name='os',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shhost',
            name='rebootrequired',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='shhost',
            name='vms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shvirtualmachine',
            name='compliant',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='shvirtualmachine',
            name='installedupdate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shvirtualmachine',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shvirtualmachine',
            name='lastcu',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shvirtualmachine',
            name='lastscantime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shvirtualmachine',
            name='os',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shvirtualmachine',
            name='rebootrequired',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='shvirtualmachine',
            name='vmid',
            field=models.UUIDField(default=uuid.UUID('42700d8d-03d5-45d5-b510-f074b61f22a7')),
        ),
    ]
