# Generated by Django 2.2.2 on 2019-06-19 03:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('LA', '0008_auto_20190613_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='redhost',
            name='osversion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='redvirtualmachine',
            name='osversion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shhost',
            name='osversion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shvirtualmachine',
            name='osversion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='redvirtualmachine',
            name='vmid',
            field=models.UUIDField(default=uuid.UUID('849e7f14-a824-4f5d-b32f-0883e051f464')),
        ),
        migrations.AlterField(
            model_name='shvirtualmachine',
            name='vmid',
            field=models.UUIDField(default=uuid.UUID('c7cef35f-549b-4bcd-9a40-9e79c0dbd3a3')),
        ),
    ]
