# Generated by Django 2.2.2 on 2019-06-19 08:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('LA', '0009_auto_20190618_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='AzureVirtualMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_name', models.CharField(max_length=200)),
                ('vmid', models.UUIDField(default=uuid.UUID('ebc4bd97-8e5c-4afe-9d49-2ebad787b61b'))),
                ('ip', models.GenericIPAddressField(null=True)),
                ('owner', models.CharField(blank=True, max_length=200, null=True)),
                ('os', models.CharField(max_length=200, null=True)),
                ('osversion', models.CharField(blank=True, max_length=200, null=True)),
                ('installedupdate', models.TextField(null=True)),
                ('lastcu', models.CharField(max_length=200, null=True)),
                ('compliant', models.BooleanField(default=True)),
                ('lastscantime', models.DateTimeField(null=True)),
                ('rebootrequired', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='redhost',
            name='owner',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='redvirtualmachine',
            name='owner',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='redvirtualmachine',
            name='vmid',
            field=models.UUIDField(default=uuid.UUID('6628c653-5b8e-44d9-94b5-1371a815f7b2')),
        ),
        migrations.AlterField(
            model_name='shhost',
            name='owner',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shvirtualmachine',
            name='owner',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shvirtualmachine',
            name='vmid',
            field=models.UUIDField(default=uuid.UUID('13dfd7b4-eb08-49e1-a44b-f53aa5418c04')),
        ),
    ]
