# Generated by Django 2.2.2 on 2019-06-19 08:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('LA', '0011_auto_20190619_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azurevirtualmachine',
            name='vmid',
            field=models.UUIDField(default=uuid.UUID('20bc2264-9542-405f-823d-753be7288318')),
        ),
        migrations.AlterField(
            model_name='redvirtualmachine',
            name='vmid',
            field=models.UUIDField(default=uuid.UUID('ad1e9bb9-54df-4abf-8918-25fab353e2ab')),
        ),
        migrations.AlterField(
            model_name='shvirtualmachine',
            name='vmid',
            field=models.UUIDField(default=uuid.UUID('442213cd-dfae-4161-bb40-0905e9857632')),
        ),
    ]
