# Generated by Django 2.2.2 on 2019-06-19 10:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('LA', '0012_auto_20190619_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azurevirtualmachine',
            name='vmid',
            field=models.UUIDField(default=uuid.UUID('3fd417a8-b607-44b3-8f72-6b8ba8bdcbbe')),
        ),
        migrations.AlterField(
            model_name='redhost',
            name='installedupdate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='redhost',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='redhost',
            name='lastcu',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='redhost',
            name='lastscantime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='redhost',
            name='os',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='redhost',
            name='vms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='redvirtualmachine',
            name='vmid',
            field=models.UUIDField(default=uuid.UUID('a276e8b8-af73-4525-b3d0-4f9e9852f188')),
        ),
        migrations.AlterField(
            model_name='shvirtualmachine',
            name='vmid',
            field=models.UUIDField(default=uuid.UUID('30d0c199-538f-4f32-b7e4-b2d3b8ea8a5b')),
        ),
    ]
