# Generated by Django 2.2.2 on 2019-06-19 10:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('LA', '0013_auto_20190619_0302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='azurevirtualmachine',
            old_name='vm_name',
            new_name='azname',
        ),
        migrations.RemoveField(
            model_name='azurevirtualmachine',
            name='vmid',
        ),
        migrations.AddField(
            model_name='azurevirtualmachine',
            name='obsolete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='azurevirtualmachine',
            name='compliant',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='azurevirtualmachine',
            name='installedupdate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='azurevirtualmachine',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='azurevirtualmachine',
            name='lastcu',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='azurevirtualmachine',
            name='lastscantime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='azurevirtualmachine',
            name='os',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='redvirtualmachine',
            name='vmid',
            field=models.UUIDField(default=uuid.UUID('80980816-f733-491d-869e-1671ca4e6f6c')),
        ),
        migrations.AlterField(
            model_name='shvirtualmachine',
            name='vmid',
            field=models.UUIDField(default=uuid.UUID('2f3b0df5-1012-4c0d-9d69-f4fb896e686e')),
        ),
    ]
