# Generated by Django 2.2.2 on 2019-06-21 10:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('LA', '0014_auto_20190619_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='redvirtualmachine',
            name='domainname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='redvirtualmachine',
            name='fullyqualifieddomainname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shvirtualmachine',
            name='domainname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shvirtualmachine',
            name='fullyqualifieddomainname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='redvirtualmachine',
            name='vmid',
            field=models.UUIDField(default=uuid.UUID('8b4f9fb9-a3b4-4055-8518-a57e806088a7')),
        ),
        migrations.AlterField(
            model_name='shvirtualmachine',
            name='vmid',
            field=models.UUIDField(default=uuid.UUID('f7dcefe1-d893-49aa-bca0-fa1f7d626aef')),
        ),
    ]
