# Generated by Django 2.2.2 on 2019-06-22 13:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('LA', '0015_auto_20190621_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='redhost',
            name='msg',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='redhost',
            name='oslang',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='redhost',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='redvirtualmachine',
            name='msg',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='redvirtualmachine',
            name='oslang',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='redvirtualmachine',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shhost',
            name='msg',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shhost',
            name='oslang',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shhost',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shvirtualmachine',
            name='msg',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shvirtualmachine',
            name='oslang',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shvirtualmachine',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='redvirtualmachine',
            name='vmid',
            field=models.UUIDField(default=uuid.UUID('07d1fd3d-b6b2-41c7-a017-bba02cb78699')),
        ),
        migrations.AlterField(
            model_name='shvirtualmachine',
            name='vmid',
            field=models.UUIDField(default=uuid.UUID('b402cdea-f5fb-45af-803e-e13c69f3ec53')),
        ),
    ]
