# Generated by Django 2.2.2 on 2019-06-23 10:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('LA', '0016_auto_20190622_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redhost',
            name='rebootrequired',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='redvirtualmachine',
            name='rebootrequired',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='redvirtualmachine',
            name='vmid',
            field=models.UUIDField(default=uuid.UUID('0267d500-997a-44ce-9ba5-552b539d1487')),
        ),
        migrations.AlterField(
            model_name='shhost',
            name='rebootrequired',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='shvirtualmachine',
            name='rebootrequired',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='shvirtualmachine',
            name='vmid',
            field=models.UUIDField(default=uuid.UUID('89ed2c37-4a8c-47ee-bd22-75bf29545b6a')),
        ),
    ]
