# Generated by Django 2.2.2 on 2019-06-25 10:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('LA', '0017_auto_20190623_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redvirtualmachine',
            name='vmid',
            field=models.UUIDField(default=uuid.UUID('62850799-5bf7-4eae-b319-1f400d0f0bb0')),
        ),
        migrations.AlterField(
            model_name='shhost',
            name='host_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='shvirtualmachine',
            name='vmid',
            field=models.UUIDField(default=uuid.UUID('8e69d04d-57e9-4966-a281-a6a9ba2d0e5b')),
        ),
    ]
