# Generated by Django 2.2.2 on 2019-06-25 10:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('LA', '0018_auto_20190625_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redhost',
            name='host_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='redvirtualmachine',
            name='vmid',
            field=models.UUIDField(default=uuid.UUID('08621741-76c5-4182-8d1f-66762ebdcd2e')),
        ),
        migrations.AlterField(
            model_name='shvirtualmachine',
            name='vmid',
            field=models.UUIDField(default=uuid.UUID('3bc7b07e-6b39-49f0-8726-fbedd85210a0')),
        ),
    ]
