# Generated by Django 2.2.2 on 2019-06-25 11:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('LA', '0019_auto_20190625_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redvirtualmachine',
            name='vmid',
            field=models.UUIDField(default=uuid.UUID('903ab2f1-cd0c-453b-904b-7118544d1bd5')),
        ),
        migrations.AlterField(
            model_name='shvirtualmachine',
            name='vmid',
            field=models.UUIDField(default=uuid.UUID('888e778e-f308-47ab-a04f-05fa438b21b5')),
        ),
    ]
