# Generated by Django 2.2.2 on 2019-07-03 05:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('LA', '0020_auto_20190625_0453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='azurevirtualmachine',
            old_name='azname',
            new_name='azmname',
        ),
        migrations.RemoveField(
            model_name='azurevirtualmachine',
            name='obsolete',
        ),
        migrations.AddField(
            model_name='azurevirtualmachine',
            name='domainname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='azurevirtualmachine',
            name='fullyqualifieddomainname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='azurevirtualmachine',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='azurevirtualmachine',
            name='msg',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='azurevirtualmachine',
            name='oslang',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='azurevirtualmachine',
            name='resourcegroupname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='azurevirtualmachine',
            name='resourceid',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='azurevirtualmachine',
            name='resourcename',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='azurevirtualmachine',
            name='role',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='azurevirtualmachine',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='azurevirtualmachine',
            name='compliant',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='azurevirtualmachine',
            name='installedupdate',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='azurevirtualmachine',
            name='ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='azurevirtualmachine',
            name='lastcu',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='azurevirtualmachine',
            name='lastscantime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='azurevirtualmachine',
            name='os',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='azurevirtualmachine',
            name='rebootrequired',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='redvirtualmachine',
            name='vmid',
            field=models.UUIDField(default=uuid.UUID('1ed4cc30-8507-4f64-ad23-a18ef533d217')),
        ),
        migrations.AlterField(
            model_name='shvirtualmachine',
            name='vmid',
            field=models.UUIDField(default=uuid.UUID('ccddc23f-4d6f-4156-a65c-3d88463eb4ba')),
        ),
    ]
