# Generated by Django 2.2.2 on 2019-07-24 08:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('LA', '0022_auto_20190724_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redvirtualmachine',
            name='vmid',
            field=models.UUIDField(default=uuid.UUID('0a734afc-62b0-4ffc-a5d9-e0d713b096cb')),
        ),
        migrations.AlterField(
            model_name='shvirtualmachine',
            name='vmid',
            field=models.UUIDField(default=uuid.UUID('e4a9f77f-204e-4f43-ac4c-505ab1bc79c8')),
        ),
    ]
