# Generated by Django 2.2.4 on 2019-11-12 14:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('LA', '0024_auto_20190730_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='redhost',
            name='sqlversion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='redhost',
            name='vsinstalled',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='redvirtualmachine',
            name='sqlversion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='redvirtualmachine',
            name='vsinstalled',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shhost',
            name='sqlversion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shhost',
            name='vsinstalled',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shvirtualmachine',
            name='sqlversion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shvirtualmachine',
            name='vsinstalled',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='redvirtualmachine',
            name='vmid',
            field=models.UUIDField(default=uuid.UUID('7a815bd8-0377-4a5a-91b9-1056d4e07eb1')),
        ),
        migrations.AlterField(
            model_name='shvirtualmachine',
            name='vmid',
            field=models.UUIDField(default=uuid.UUID('4d826801-0ec7-4ef9-989a-fa0e17457241')),
        ),
    ]
